package parser

import (
	"github.com/sylphon/build-runner/parser/uuid"
)

/*
NextUUID returns the next UUID generated by the parser's uuid generator.  This
will either be a random uuid (normal behavior) or the same uuid every time if
the generator is "seeded" (used for tests)
*/
func (parser *Parser) NextUUID() (string, error) {
	return parser.uuidGenerator.NextUUID()
}

/*
RandomizeUUIDGenerator turns this parser's uuidGenerator into a random
generator.  All calls to NextUUID() will produce a random uuid after this
function is called and until SeedUUIDGenerator() is called.
*/
func (parser *Parser) RandomizeUUIDGenerator() {
	parser.uuidGenerator = uuid.NewUUIDGenerator()
}
